using Microsoft.AspNetCore.Connections;
using TheDesolatedTunnels.RelayServer.Core.Domain;

namespace TheDesolatedTunnels.RelayServer.Core.Interfaces.Services
{
    /// <summary>
    ///     Interface IMessageHandler
    /// </summary>
    /// <autogeneratedoc />
    public interface IMessageHandler
    {
        SixtyNineSendibleMessage? HandleMessage(ConnectionContext connection, SixtyNineMessage message);
    }
}