using System;

namespace Rocco.RelayServer.Core.Domain.Exceptions;

/// <summary>
///     Class ConnectionNotFoundException.
///     Implements the <see cref="System.Exception" />
/// </summary>
/// <seealso cref="System.Exception" />
/// <autogeneratedoc />
public class ConnectionNotFoundException : Exception
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="ConnectionNotFoundException" /> class.
    /// </summary>
    /// <param name="connectionId">The connection identifier.</param>
    /// <autogeneratedoc />
    public ConnectionNotFoundException(string connectionId) : base(connectionId)
    {
    }
}