namespace TheDesolatedTunnels.RelayServer.Core.Domain
{
    /// <summary>
    ///     Enum SixtyNineMessageType
    /// </summary>
    /// <autogeneratedoc />
    public enum SixtyNineMessageType
    {
        /// <summary>
        ///     The initialize
        /// </summary>
        /// <autogeneratedoc />
        Init,

        /// <summary>
        ///     The payload
        /// </summary>
        /// <autogeneratedoc />
        Payload,

        /// <summary>
        ///     The close
        /// </summary>
        /// <autogeneratedoc />
        Close,

        /// <summary>
        ///     The error
        /// </summary>
        /// <autogeneratedoc />
        Error
    }
}