using Microsoft.AspNetCore.Connections;
using Rocco.RelayServer.Core.Domain;

namespace Rocco.RelayServer.Core.Interfaces.Services
{
    /// <summary>
    ///     Interface IMessageHandler
    /// </summary>
    /// <autogeneratedoc />
    public interface IMessageHandler
    {
        SixtyNineMessage? HandleMessage(ConnectionContext connection, SixtyNineMessage message);
    }
}