using System.Net;
using Bedrock.Framework;
using Bedrock.Framework.Protocols;
using Microsoft.AspNetCore.Connections;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Rocco.RelayServer.Core.Interfaces.Services;
using Rocco.RelayServer.Core.Domain;
using Rocco.RelayServer.Core.Server.ConnectionHandlers;
using Rocco.RelayServer.Core.Server.Helpers;
using Rocco.RelayServer.Core.Server.Services;
using Rocco.RelayServer.Core.Services;

namespace Rocco.RelayServer
{
    /// <summary>
    ///     Class Program.
    /// </summary>
    /// <autogeneratedoc />
    internal static class Program
    {
        /// <summary>
        ///     Defines the entry point of the application.
        /// </summary>
        /// <param name="args">The arguments.</param>
        /// <autogeneratedoc />
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        /// <summary>
        ///     Creates the host builder.
        /// </summary>
        /// <param name="args">The arguments.</param>
        /// <returns>IHostBuilder.</returns>
        /// <autogeneratedoc />
        private static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args)
                .ConfigureLogging((hostContext, loggingBuilder) =>
                {
                    loggingBuilder.SetMinimumLevel(LogLevel.Debug);
                })
                .ConfigureDefaultRelayWithFakeCaller(IPAddress.Any);
        }
    }
}